### ISSUE TITLE
Create Incubator Helm Chart for Kubernetes Deployment

### ISSUE THREAD

**Issue by lbontecou** [optimizely/agent#167]
Kubernetes deployments of this agent should be a major use-case. Many similar open-source tools maintain a well documented Helm Chart that simplifies this process. 

https://github.com/helm/charts/tree/master/stable

Getting a bare bones v0.1 into the incubator would help to encourage community contributions. I'm personally expecting to use this workflow to deploy out the agent within the next few weeks, I'd love to have a template to work from and contribute my modifications back. 

https://github.com/helm/charts/tree/master/incubator

**Comment by Tamara-Barum** [comment]
Closed as fixed with PR 319
