### ISSUE TITLE
Getting an error when setting up project

### ISSUE THREAD

**Issue by kbeckerDE** [optimizely/agent#302]
I'm on macOS 10.15.7. I installed Golang version 1.16, cloned the repo, cd'ed into the directory and ran "make setup". I got the following:

mbp2a95:agent kbecker$ make setup
golangci/golangci-lint info checking GitHub for tag 'v1.19.0'
golangci/golangci-lint info found version: 1.19.0 for v1.19.0/darwin/amd64
golangci/golangci-lint info installed /Users/kbecker/go/bin/golangci-lint
go: downloading github.com/rakyll/statik v0.1.7
"# runtime/cgo"
In file included from cgo-builtin-prolog:1:
/usr/local/include/stddef.h:40:10: fatal error: '__config' file not found
#include <__config>
         ^~~~~~~~~~
1 error generated.
make: *** [setup] Error 2

Does anyone know how to solve this issue? (I added quotes around the runtime/cgo line to prevent the formatting)

**Comment by msohailhussain** [comment]
Hi @kbeckerDE 
Are you still facing the same issue, we tried it and not getting any error. Please feel free to open this ticket again if you are facing the issue.
thanks,
Sohail
