### ISSUE TITLE
📣 I made a helm chart.

### ISSUE THREAD

**Issue by kieranajp** [optimizely/agent#319]
_(Opening this as a new issue rather than piggybacking off https://github.com/optimizely/agent/issues/167, because I don't know if anyone from Optimizely is still following that thread)_

Hey Optimizely folk,

This morning I threw together https://github.com/kieranajp/optimizely-agent-helm and used it to host the agent on my workplace's K8s cluster. We'll be starting using this in production in the coming days.

As there's clearly some interest in Helm support for this chart - #167, #265 (that happens to be from exactly a year ago!) - I thought to reach out in case you're interested in either transitioning the repository over to your org, or linking to it as an unofficial chart.

If you're interested, then feel free to test it and suggest any changes - it's very early days for it yet but I will be making improvements to both the chart itself and the docs as we battle-test it a little in-house.

```sh
$ helm repo add optimizely-agent https://kieranajp.github.io/optimizely-agent-helm
$ helm install --debug optimizely-agent optimizely-agent/optimizely-agent
```

Cheers,
--Kieran

**Comment by msohailhussain** [comment]
Hi Kieran, 

Apology for the long delay to take care this helm chart feature for agent. In past few days, I tested the package that you already have it in your repo, and it works fine & more or less, the implementation is as expected what we wanted to achieve. 

There are few features which we will improve in future e.g. well defined ConfigMaps / Secrets etc for environment variables and Authenticated datafiles. 
Also, we are planning to release on artifactshub.io as well. please let us know if you are good with transferring ownership, can you please transfer it to 'Optimizely' org.

thanks,
Sohail

**Comment by msohailhussain** [comment]
@kieranajp tagging you.

**Comment by kieranajp** [comment]
Hey, sorry about this. I think the notifications got lost amongst other ones.

I see that you were able to use my chart when creating an official one. Do you still need anything from me?

**Comment by msohailhussain** [comment]
Thanks. Feel free to comment on optimizely/optimizely-agent-helm repo.
