### ISSUE TITLE
Unable to use /oauth/token since version 2.0.0

### ISSUE THREAD

**Issue by LieneJansone** [optimizely/agent#345]
There is an issue with authentification using [Issuer & Validator ](https://docs.developers.optimizely.com/full-stack/docs/authorization#issuer--validator) scheme since version 2.0.0

Issue description:
`oauth/token` endpoint is expecting `Content-Type: application/json` [here](https://github.com/optimizely/agent/blob/master/pkg/routers/api.go#L155), but `auth` service is expecting `Content-Type: application/x-www-form-urlencoded`  [here](https://github.com/optimizely/agent/blob/master/pkg/handlers/oauth.go#L127)

To reproduce:
1. Not passing `Context-Type` header => returns `415` error code
```
#!/usr/bin/python3

import json
import requests
import sys

s = requests.Session()
s.headers.update({'X-Optimizely-SDK-Key': "mySDKkey"})

resp = s.post('http://localhost:8080/oauth/token', data={
    "grant_type": "client_credentials",
    "client_id":  "myclientID",
    "client_secret": "myclientSecret",
})

print(resp)
```

2. Passing `Context-Type: application/json` header => returns `400` error code
```
#!/usr/bin/python3

import json
import requests
import sys

s = requests.Session()
s.headers.update({'X-Optimizely-SDK-Key': "mySDKkey"})
s.headers.update({'Content-Type': 'application/json'})

resp = s.post('http://localhost:8080/oauth/token', data={
    "grant_type": "client_credentials",
    "client_id":  "myclientID",
    "client_secret": "myclientSecret",
})

print(resp)
```
We are using a custom build image with a workaround of removing `contentTypeMiddleware` from [here](https://github.com/optimizely/agent/blob/master/pkg/routers/api.go#L155)

Could this be looked into please? :)

**Comment by Tamara-Barum** [comment]
Closing as this was fixed in PR 346
